export const bestPracticesList = [
    "Bonuses Project team",
    "Subcontractors",
    "Stripe fee",
    "Marketing team salary",
    "R&D team salary",
    "Recruitment expenses",
    "Salary G&A",
    "Legal consultancy",
    "Rent",
    "Comissions and fees",
    "Salary, taxes & bonuses",
    "Sales team salary",
    "Federal Taxes",
    "1 Essential subscription",
    "Income from Operational Activity",
    "Sales of property and equipment",
    "Receiving of loans",
    "Purchase of property and equipment",
    "Dividends paid",
    "Internal (\"-\")",
    "Project team salary",
    "FP&A team software expenses",
    "Marketing salary Tax",
    "R&D team salary tax expenses",
    "Education",
    "Salary G&A Tax Expenses",
    "Financial consultancy",
    "Facilities",
    "Other general and administrative expenses",
    "Sales bonus",
    "State Taxes",
    "1 Growth subscription",
    "Sales of intangible assets",
    "Proceeds from debt",
    "Purchase of intangible assets",
    "Repayment of loans",
    "Internal (\"+\")",
    "Project team salary tax",
    "Marketing team bonuses",
    "R&D software & other services",
    "Corporate events",
    "Administrative team bonuses",
    "Bookkeeping",
    "Other office expenses",
    "Social Tax",
    "Sales salary Tax",
    "1 Custom subscription",
    "Proceeds from the issue of share capital",
    "Principal repayment of lease obligations",
    "Correction",
    "Advertising",
    "R&D team bonuses",
    "Other staff expenses",
    "Other subcontractors",
    "Office equipment",
    "PE Tax",
    "Sales software & other services",
    "1 Bookkeeping subscription",
    "Grants and other non-operating  income",
    "Interest Loss",
    "Digital Marketing",
    "Operational software",
    "Financial & legal software",
    "Refferal program",
    "1 Bookkeeping (reporting)",
    "Interest Income",
    "Foreign Exchange Loss",
    "Design",
    "Recruitment software",
    "Other sales expenses",
    "1 Financial Modeling",
    "Foreign Exchange Gain",
    "Issue of loans to employee",
    "Content creation (newsletters, blog, social media)",
    "1 Income from Other Services",
    "Repayment of loans to employee",
    "PR",
    "1 Consulting",
    "Fuel Events",
    "Other income",
    "Offline events + travelling expenses",
    "Less: Discount",
    "Website improvements",
    "Less: Refferal discount",
    "SEO",
    "Bad Debt",
    "Marketing software & other services",
    "Other marketing expenses"
];
